training_files: 
  - C:\Users\tomic\ml\projects\dns_exfil_mbert\data\processed\train.txt
  - C:\Users\tomic\ml\projects\dns_exfil_mbert\data\processed\val.txt
  - C:\Users\tomic\ml\projects\dns_exfil_mbert\data\processed\test.txt
save_dir: C:\Users\tomic\ml\projects\dns_exfil_mbert\artifacts\tokenizer\bpe\bpe8k