name: dns-bert
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - tqdm
  - jsonschema
  - tokenizers
  - ipykernel
  - sentencepiece
  - datasets
  - wandb
  - hydra-core
  - omegaconf
  - pip
  - pip:
      - torch>=2.1.0
      - torchmetrics
      - torchvision
      - torchaudio
      - transformers>=4.35.0
      - accelerate>=0.26.0
      - tensorflow
      - tf-keras
      - tensorboard
      - hypothesis
      - pytest
      - pytest-benchmark
      - pytest-cov
      - black
      - flake8
      - mypy
