[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dns_exfil_mbert"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 79

[tool.mypy]
ignore_missing_imports = true