alphabet: "abcdefghijklmnopqrstuvwxyz0123456789-._"
"vocab_size" : 8000


pad_token: "[PAD]"
unk_token: "[UNK]"
cls_token: "[CLS]"
sep_token: "[SEP]"
mask_token: "[MASK]"

max_length: 256
padding: True
truncation: True