alphabet: "abcdefghijklmnopqrstuvwxyz0123456789-._?@:\\(/)`[*"

pad_token: "[PAD]"
unk_token: "[UNK]"
cls_token: "[CLS]"
sep_token: "[SEP]"
mask_token: "[MASK]"

max_length: 512
padding: True
truncation: True