alphabet: abcdefghijklmnopqrstuvwxyz0123456789-._
cls_token: '[CLS]'
mask_token: '[MASK]'
max_length: 256
pad_token: '[PAD]'
padding: true
save_dir: C:\Users\tomic\ml\projects\dns_exfil_mbert/artifacts/tokenizer/bpe/bpe8k
sep_token: '[SEP]'
special_tokens:
  cls_token: '[CLS]'
  mask_token: '[MASK]'
  pad_token: '[PAD]'
  sep_token: '[SEP]'
  unk_token: '[UNK]'
training_files:
- C:\Users\tomic\ml\projects\dns_exfil_mbert/data/processed/train.txt
- C:\Users\tomic\ml\projects\dns_exfil_mbert/data/processed/val.txt
- C:\Users\tomic\ml\projects\dns_exfil_mbert/data/processed/test.txt
truncation: true
unk_token: '[UNK]'
vocab_size: 8192
