output_dir: experiments/toy_training
overwrite_output_dir: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1e-3
weight_decay: 0.01
num_train_epochs: 30
max_steps: -1
bf16: false
fp16: false
logging_strategy: steps
logging_steps: 1
save_steps: 1000
save_total_limit: 1
eval_strategy: steps
disable_tqdm: true
eval_steps: 5
label_smoothing_factor: 0.1
report_to: none
remove_unused_columns: false

mlm_probability: 0.15
span_masking: false
span_lambda: 3.0

optimizer_type: adafactor
lr_scheduler_type: cosine
warmup_ratio: 0.01

gradient_checkpointing: false
torch_compile: false