trainer_args:
  output_dir: ${paths.output_dir}
  overwrite_output_dir: true
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.01
  num_train_epochs: 100
  max_steps: -1
  bf16: false
  fp16: false
  logging_strategy: steps
  logging_steps: 1
  save_steps: 1000
  save_total_limit: 1
  eval_strategy: steps
  disable_tqdm: true
  eval_steps: 5
  label_smoothing_factor: 0.1
  report_to: 
    - tensorboard
  logging_dir: ${paths.tensorboard}
  remove_unused_columns: false

  optimizer_type: adamw
  lr_scheduler_type: linear
  warmup_ratio: 0.01

  gradient_checkpointing: false
  torch_compile: false

mask_args:
  mlm_probability: 0.15
  strategy: token
  span_lambda: 3.0
  seed: 42
MLM_collator_args:
  pad_to_multiple_of: 8
  mask_token_prob: 0.8
  random_token_prob: 0.1
CLS_collator_args:
  pad_to_multiple_of: 8
  label_key: label
  convert_to_one_hot: false
  num_labels: 2