files:
  train:
    - ${hydra:runtime.cwd}/data/raw/normalized/train.csv
  validation:
    - ${hydra:runtime.cwd}/data/raw/normalized/val.csv
  test:
    - ${hydra:runtime.cwd}/data/raw/normalized/test.csv

data_dir: ${hydra:runtime.cwd}/data/processed/labeled_dataset