mlm_files:
  train:
    - ${paths.data}/mlm/train.csv
  validation:
    - ${paths.data}/mlm/val.csv
  test:
    - ${paths.data}/mlm/test.csv
cls_files:
  train:
    - ${paths.data}/cls/train.csv
  validation:
    - ${paths.data}/cls/val.csv
  test:
    - ${paths.data}/cls/test.csv

MLM_builder_args:
  raw_files: ${dataset.mlm_files}
  streaming: false
  max_length: 256
  cache_dir: ${paths.root}/experiments/cache/mlm
  force_rebuild: false

CLS_builder_args:
  raw_files: ${dataset.cls_files}
  streaming: false
  max_length: 512
  cache_dir: ${paths.root}/experiments/cache/cls
  force_rebuild: false