files:
  train:
    - ${paths.data}/deduped/train.csv
  validation:
    - ${paths.data}/deduped/val.csv
  test:
    - ${paths.data}/deduped/test.csv

MLM_builder_args:
  raw_files: ${dataset.files}
  streaming: false
  max_length: 256
  proportion: 
    train: 0.8
    validation: 0.1
    test: 0.1
  cache_dir: ${paths.root}/experiments/cache
  force_rebuild: false

CLS_builder_args:
  raw_files: ${dataset.files}
  streaming: false
  max_length: 256
  proportion: 
    train: 0.8
    validation: 0.1
    test: 0.1
  cache_dir: ${paths.root}/experiments/cache
  force_rebuild: false