defaults:
  - _self_
  - paths
  - tokenizer:   bpe8k_pretrained
  - training_arguments: args_for_bpe8k_reg_dataset_train_run
  - dataset:    dataset_for_mlm
  - model:      bert_uncased
  - model_config: bert_bpe_8k_reg_dataset_cfg
