defaults:
  - _self_
  - paths
  - tokenizer:   bpe8k_pretrained
  - training_arguments: args_for_conv_test
  - dataset:    dataset_for_mlm
  - model:      bert_uncased
  - model_config: bert_config_fr
