hydra:
  sweep:
    dir: /out
  run:
    dir: ${hydra.sweep.dir}

paths:
  root: ${oc.env:EXPDIR}
  data: /data/${oc.env:DATASET}
  artifacts: ${paths.root}/artifacts
  out: ${parent:${hydra:runtime.output_dir}}
  output_dir: ${paths.out}${num:${hydra:job.num}}
  tensorboard: ${paths.out}/log/tensorboard${num:${hydra:job.num}}