name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: ci-env

      - name: Activate Conda & install dev tools
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # only install the tools you need—no transformer stubs
          pip install pytest

      - name: Run tests
        shell: bash -l {0}
        run: pytest --maxfail=1 --disable-warnings -q